public class inv_QuoteTriggerHandler {
    
    public static Boolean disableTrigger = false;


    // public static void handleAfterTrigger(List<Quote> listNew, Map<Id, Quote> oldMap, Boolean isInsert, Boolean isUpdate, Boolean isDelete) {

    //     for(Quote quote : listNew){
            
    //         if(oldMap.get(quote.Id).Status != quote.Status && quote.Status == 'Accepted'){
    //             createInvoiceCallout.createInvoice(quote.Id, oldMap.get(quote.Id).Status, quote.Status);

    //         }
           

    //     }

    // }
}